### ISSUE TITLE
RS5k manager: Macro/Sampler | Some parameters leave their boundaries when linked

### ISSUE THREAD

**Issue by IOphonics** [MichaelPilyavskiy/ReaScripts#43]
Without linking 'Attack' has a range from 0 to 500ms. When linked it goes from 0 to 2000ms. 'Decay', 'Release' and 'Loop' show similar behaviour (with different values though).

**Comment by MichaelPilyavskiy** [comment]
It is a nitpick due to fixed sample values. For example, sample id 250ms long but the attack still 2s. RS5k manager handle UI controls and make min max for attack as 0...250ms but when doing something from REAPER side (linking for example), it connects to full range. I would play with offsets here, but controls are logarithmic, so I cant do anything here.
